# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shockburst.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from lib.DroneNet.sim import nanopb_pb2 as nanopb__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='shockburst.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10shockburst.proto\x1a\x0cnanopb.proto\"C\n\x12ShockBurstResponse\x12\x0e\n\x06sender\x18\x01 \x02(\x04\x12\x0b\n\x03\x61\x63k\x18\x02 \x02(\x08\x12\x10\n\x08\x66rame_id\x18\x03 \x02(\r\"k\n\x0fShockBurstFrame\x12\x16\n\x06sender\x18\x01 \x02(\x0c\x42\x06\x92?\x03\x08\x80\x01\x12\x0b\n\x03\x63rc\x18\x02 \x02(\r\x12\x0c\n\x04type\x18\x03 \x02(\r\x12\x10\n\x08\x66rame_id\x18\x04 \x02(\r\x12\x13\n\x04\x64\x61ta\x18\x05 \x02(\x0c\x42\x05\x92?\x02\x08 '
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])




_SHOCKBURSTRESPONSE = _descriptor.Descriptor(
  name='ShockBurstResponse',
  full_name='ShockBurstResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='ShockBurstResponse.sender', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ack', full_name='ShockBurstResponse.ack', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='ShockBurstResponse.frame_id', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=101,
)


_SHOCKBURSTFRAME = _descriptor.Descriptor(
  name='ShockBurstFrame',
  full_name='ShockBurstFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='ShockBurstFrame.sender', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\003\010\200\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crc', full_name='ShockBurstFrame.crc', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='ShockBurstFrame.type', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='ShockBurstFrame.frame_id', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='ShockBurstFrame.data', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\002\010 ', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=210,
)

DESCRIPTOR.message_types_by_name['ShockBurstResponse'] = _SHOCKBURSTRESPONSE
DESCRIPTOR.message_types_by_name['ShockBurstFrame'] = _SHOCKBURSTFRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShockBurstResponse = _reflection.GeneratedProtocolMessageType('ShockBurstResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHOCKBURSTRESPONSE,
  '__module__' : 'shockburst_pb2'
  # @@protoc_insertion_point(class_scope:ShockBurstResponse)
  })
_sym_db.RegisterMessage(ShockBurstResponse)

ShockBurstFrame = _reflection.GeneratedProtocolMessageType('ShockBurstFrame', (_message.Message,), {
  'DESCRIPTOR' : _SHOCKBURSTFRAME,
  '__module__' : 'shockburst_pb2'
  # @@protoc_insertion_point(class_scope:ShockBurstFrame)
  })
_sym_db.RegisterMessage(ShockBurstFrame)


_SHOCKBURSTFRAME.fields_by_name['sender']._options = None
_SHOCKBURSTFRAME.fields_by_name['data']._options = None
# @@protoc_insertion_point(module_scope)
